services:
  backend:
    build: ./backend
    image: engram-be:dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - hf_cache:/root/.cache/huggingface
    depends_on:
      - qdrant
      - postgres

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: engram_user
      POSTGRES_PASSWORD: engram_pass
      POSTGRES_DB: engram_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  qdrant_data:
  postgres_data:
  hf_cache:
